### ISSUE TITLE
Duplicate claims caused by some html chars

### ISSUE THREAD

**Issue by ypesk** [CIMPLE-project/converter#11]
Some characters cause claims text to appear multiple times.

Example: https://data.cimple.eu/claim/9be6755327a7f93a10af1ffa5b7a6f71a9b7be7818a959bfa4fae2fd
has multiple schema:text associated:
1. In a video displayed during U.S. President Donald Trump's second impeachment trial on Feb. 9, 2021, House Democrats did not show footage of Trump telling supporters on Jan. 6 to \&quot;peacefully and patriotically make your voices heard.\&quot;
2. In a video displayed during U.S. President Donald Trump's second impeachment trial on Feb. 9, 2021, House Democrats did not show footage of Trump telling supporters on Jan. 6 to "peacefully and patriotically make your voices heard."

This specific example, also has two sentiment values. This can be because both text have different sentiment values, even though the only difference is the specific character.

Other examples: https://data.cimple.eu/claim/d5a6a22fdee5dd67ac5beac1e34c6e761d11ac3648948176f692fc6f
https://data.cimple.eu/claim/7a45236dae17d72f2bdcab8c8c1b46febd4d5f04b7e87b2572c99f60

Decoding  \&quot; as " would probably resolve the issue. We might have the problem with other special characters.

**Comment by rtroncy** [comment]
Good catch @ypesk ! Indeed, we need to be at least agnostic of the resolution of the HTML entity `&quot;` (aka `"`) and we may want to escape a number of other HTML entities. @ehrhart Can you please look into this?

**Comment by ehrhart** [comment]
I suggest to use [html.unescape(s)](https://docs.python.org/3/library/html.html#html.unescape) to resolve the HTML characters.

For existing dumps, we can either:
1. Re-process all the datasets and generate new dumps. This might take a while considering the size of the data, and isn't very efficient.
2. Write a script which takes the existing dump, and for each claim we generate an UUID with the unescaped version of the text. Then we check for these two conditions: (1) if the new UUID is different than the original one, and (2) if the new UUID already exists in the dump. If this is the case, we assume it is a duplicate due to HTML characters, and we remove this claim from the dump.

**Comment by rtroncy** [comment]
I like the solution 2. for the existing dump. @ehrhart Do you mind coding this script and launching the process to see how many potential duplicates we would get? We could validate these manually depending on their number.

Regarding the current nightly process, do you mind @ehrhart making a pull request as where [html.unescape(s)](https://docs.python.org/3/library/html.html#html.unescape) should be used?

**Comment by ehrhart** [comment]
After further investigation it looks like the dumps do not contain the erroneous HTML entities. It seems that the issue was related to KG containing outdated data which was out of sync.
I've cleared the graph <http://data.cimple.eu/graph/claimreview> and re-uploaded the dump into the KG.
This seems to have fixed the issue.
